TUM-30-files-list-frontend
Camed/Tumultu_Project pull request #13
Opened 2024-02-16 13:47 UTC by ketrab100

2024-02-26 17:40 UTC, PaterMajkel requested changes
Change some things so it would be easier to work on it in the future

2024-02-26 17:40 UTC, PaterMajkel commented on Frontend/Tumultu/src/app/file/api/index.ts
you don't have to export files like that in angular project. Simple export interface in a model file is more than enough

2024-02-26 17:40 UTC, PaterMajkel commented on Frontend/Tumultu/src/app/file/api/models/response/index.ts
same as earlier

2024-02-26 17:40 UTC, PaterMajkel commented on Frontend/Tumultu/src/app/file/list/components/files-list/files-list.component.html
> +  <div *ngFor="let file of files | async">
just an Idea, we can implement new angular syntax for iterations in .html file:

@for (file of files | async; ) {
  <mat-list-item>....
}

New syntax provides easier methods to implement empty list alerts and many different useful templates

2024-02-26 17:40 UTC, PaterMajkel commented on Frontend/Tumultu/src/app/file/list/components/files-list/files-list.component.ts
> +    console.log();
leftover console.log

2024-02-26 17:40 UTC, PaterMajkel commented on Frontend/Tumultu/src/app/file/shared/stores/files.store.ts
I think it's better to export an observable in getFiles and when updating the store we would just use files$$.next(files)
right now after seting behaviourSubject we would be never able to gather an updated value

2024-02-27 17:22 UTC, ketrab100 commented on Frontend/Tumultu/src/app/file/shared/stores/files.store.ts
subject should be modified only inside of the store https://stackoverflow.com/questions/73648114/why-is-it-recommended-to-make-subjects-in-your-service-private-and-just-expose

2024-02-27 17:39 UTC, ketrab100 commented on Frontend/Tumultu/src/app/file/api/index.ts
Barrel files just simplify imports

2024-03-09 18:36 UTC, PaterMajkel approved these changes

2024-03-10 12:39 UTC, merged